image: openjdk:17-alpine

stages:
  - lint
  - build
  - test

checkstyle:
  stage: lint
  before_script:
    - cd back-end
    - chmod 777 ./gradlew
  script:
    - ./gradlew check
  artifacts:
    paths:
      - back-end/build/reports/checkstyle/
    expire_in: 1 week

build-gradle:
  stage: build
  before_script:
    - cd back-end
  script:
    - ./gradlew build
  artifacts:
    paths:
      - back-end/build/libs
    expire_in: 1 week

test-gradle:
  stage: test
  before_script:
    - cd back-end
  script:
    - ./gradlew test
